services:
  postgres:
    image: postgres:17
    container_name: my-better-t-app
    restart: always
    environment:
      POSTGRES_DB: my-better-t-app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
